<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_vaccine_patient_tests.TestVaccinePatient-20220523162026" tests="6" file="test_vaccine_patient_tests.py" time="0.172" timestamp="2022-05-23T16:20:27" failures="0" errors="0" skipped="1">
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_bad_date_signature" time="0.076" timestamp="2022-05-23T16:20:27"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_no_date" time="0.022" timestamp="2022-05-23T16:20:27"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_not_found_date_signature" time="0.026" timestamp="2022-05-23T16:20:27"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_ok" time="0.019" timestamp="2022-05-23T16:20:27"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_store_date_is_empty" time="0.027" timestamp="2022-05-23T16:20:27"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_no_store_date" time="0.001" timestamp="2022-05-23T16:20:27">
		<skipped type="skip" message="This exception won't be raised after the refactoring process"/>
	</testcase>
</testsuite>
